import matplotlib.pyplot as plt
from pathlib import Path
from smart_pipeline import Pipeline, IterativeSolver

# TODO implement solver that does not depend on thr order of steps added

# ==============================================================================
# 1. DEFINE A COUPLED SYSTEM (Cyclic Dependencies)
# ==============================================================================
# We define a stable system of linear equations with a cyclic dependency.
# x = 0.5 * y + 2
# y = 0.5 * z - 1
# z = 0.5 * x + 4
#
# Analytical Solution:
# Substitute z -> y, then y -> x:
#   y = 0.5(0.5x + 4) - 1 = 0.25x + 1
#   x = 0.5(0.25x + 1) + 2 = 0.125x + 2.5
#   0.875x = 2.5  => x = 2.5 / 0.875 = 20/7 ≈ 2.8571
#   y = 0.25(20/7) + 1 = 12/7 ≈ 1.7143
#   z = 0.5(20/7) + 4 = 10/7 + 28/7 = 38/7 ≈ 5.4286

def compute_x(y, history_x):
    """Calculates x based on y."""
    val = 0.5 * y + 2
    history_x.append(val)
    return val

def compute_y(z, history_y):
    """Calculates y based on z."""
    val = 0.5 * z - 1
    history_y.append(val)
    return val

def compute_z(x, history_z):
    """Calculates z based on x."""
    val = 0.5 * x + 4
    history_z.append(val)
    return val

# ==============================================================================
# 2. CONFIGURE PIPELINE
# ==============================================================================

# We monitor 'x' for convergence.
solver_config = IterativeSolver(
    target_var='y',
    tolerance=1e-6,
    max_iterations=50
)

pipe = Pipeline(solver=solver_config)

# !!! CRITICAL NOTE ON ORDER !!!
# Unlike the DAGSolver (which reorders based on dependencies), the IterativeSolver 
# is "naive" and runs steps in the exact order they are added.
# 
# Current Order: Z -> Y -> X
# Changing this order affects the "propagation speed" of the solution (Gauss-Seidel effect),
# though for this stable linear system, it will likely converge regardless.
pipe.add(compute_z, outputs=['z'])
pipe.add(compute_y, outputs=['y'])
pipe.add(compute_x, outputs=['x'])

pipe.visualize(inputs=["history_x", "history_y", "history_z"],
                output_pdf=str(Path("results") / "iterative_pipeline_diagram.pdf"),
                graph_type="bipartite")

# ==============================================================================
# 3. RUN THE SIMULATION
# ==============================================================================

# Initial guesses
initial_state = {
    'x': 0, 'y': 0, 'z': 0,
    'history_x': [0],
    'history_y': [0],
    'history_z': [0]
}

print("--- Starting Iterative Solver ---")
print("NOTE: The solver will execute steps in the registration order:")
print("      1. compute_z (updates z)")
print("      2. compute_y (updates y using new z)")
print("      3. compute_x (updates x using new y)")
print("-----------------------------------")

print("Running pipeline...")
results = pipe.run(**initial_state)

print(f"Converged Values -> X: {results['x']:.4f}, Y: {results['y']:.4f}, Z: {results['z']:.4f}")

# Verification Step
expected = {'x': 20./7., 'y': 12./7., 'z': 38./7.}
print("\n--- Verification Check ---")
for var, target in expected.items():
    actual = results[var]
    error = abs(actual - target)
    print(f"Variable {var.upper()}: Target={target}, Actual={actual:.4f} (Error={error:.4e})")

# ==============================================================================
# 4. PLOT TRAJECTORIES
# ==============================================================================

hist_x = results['history_x']
hist_y = results['history_y']
hist_z = results['history_z']
# Retrieve the residuals generated by our modified IterativeSolver
residuals = results.get('residual_history', [])

iterations = range(len(hist_x))
res_iterations = range(1, len(residuals) + 1)

# Create a figure with 2 subplots (1 row, 2 columns)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Plot 1: Variable Convergence (Updated Legends)
ax1.plot(iterations, hist_x, 'o-', label=f"x (Target {expected['x']:.6f})", markersize=4)
ax1.plot(iterations, hist_y, 's-', label=f"y (Target {expected['y']:.6f})", markersize=4)
ax1.plot(iterations, hist_z, '^-', label=f"z (Target {expected['z']:.6f})", markersize=4)
ax1.set_title('Variable Trajectories')
ax1.set_xlabel('Iteration Step')
ax1.set_ylabel('Value')
ax1.grid(True, linestyle='--', alpha=0.5)
ax1.legend()

# Plot 2: Residual History (Log Scale)
if residuals:
    ax2.plot(res_iterations, residuals, 'r-o', label='Residual (|x_new - x_old|)')
    ax2.set_yscale('log')
    ax2.set_title('Convergence Residual (Log Scale)')
    ax2.set_xlabel('Iteration Step')
    ax2.set_ylabel('Residual')
    ax2.grid(True, linestyle='--', alpha=0.5, which="both")
    ax2.legend()
else:
    ax2.text(0.5, 0.5, "No residuals recorded", ha='center')

plt.tight_layout()

print("Displaying plot...")
plt.show()