"""VERBATIM output from a coding agent, kept as evidence. Do not "fix" it.

Asked for a wing model sized from span, chord and speed, an agent produced
this. It is structurally valid, it converges, and its arithmetic checks out -
and it is nonsense: `compute_lift` consumes span/chord/speed and produces
`lift`, which NOTHING reads. The mass loop underneath is closed on itself
(structural_mass = 0.3 * total_mass, so total = payload / 0.7), so the three
variables the engineer actually asked to size the wing from have zero
influence on the answer.

The graph falls into two disconnected pieces. That is the signal
`validate()` now reports, and this file is the regression test for it.

See docs/known-issues.md and the disconnected-graph finding.
"""
import logging
from smartmdao.core import Pipeline
from smartmdao.solvers import HybridSolver
from smartmdao.logging_config import configure_logging

logger = logging.getLogger(__name__)

# ==============================================================================
# PART 1: Initialize the Pipeline with the HybridSolver
# ==============================================================================
# HybridSolver is needed because of the cyclic dependency:
# structural_mass -> total_mass -> required_lift -> structural_mass
pipeline = Pipeline(
    solver=HybridSolver(max_iterations=100, tolerance=1e-6)
)

# ==============================================================================
# PART 2: Define the wing disciplines using decorators
# ==============================================================================
AIR_DENSITY = 1.225        # kg/m^3, sea level
LIFT_COEFFICIENT = 1.2     # cruise CL
STRUCTURAL_FACTOR = 0.3    # structural mass as a fraction of required weight
GRAVITY = 9.81             # m/s^2

@pipeline.step(outputs=["lift"])
def compute_lift(span: float, chord: float, speed: float) -> float:
    """Aerodynamic lift generated by the wing at the given flight speed."""
    area = span * chord
    return 0.5 * AIR_DENSITY * speed ** 2 * area * LIFT_COEFFICIENT

@pipeline.step(outputs=["structural_mass"])
def compute_structural_mass(required_lift: float) -> float:
    """Wing structural mass needed to carry the required lift."""
    return STRUCTURAL_FACTOR * required_lift / GRAVITY

@pipeline.step(outputs=["total_mass"])
def compute_total_mass(structural_mass: float, payload_mass: float) -> float:
    """Total aircraft mass: structure plus payload."""
    return structural_mass + payload_mass

@pipeline.step(outputs=["required_lift"])
def compute_required_lift(total_mass: float) -> float:
    """Lift required for level flight: must balance total weight."""
    return total_mass * GRAVITY

# ==============================================================================
# PART 3: Execution
# ==============================================================================
def run_wing_mda():
    configure_logging(level=logging.INFO)

    logger.info("--- Running Wing Multidisciplinary Analysis (MDA) ---")

    inputs = {
        "span": 12.0,
        "chord": 1.5,
        "speed": 60.0,
        "payload_mass": 400.0,
        "total_mass": 1000.0,  # Initial guess to kick-start the mass/lift cycle
    }

    results = pipeline.run(**inputs)

    logger.info("\n--- Final Results ---")
    logger.info(f"lift             = {results['lift']:.2f} N")
    logger.info(f"structural_mass  = {results['structural_mass']:.2f} kg")
    logger.info(f"total_mass       = {results['total_mass']:.2f} kg")
    logger.info(f"required_lift    = {results['required_lift']:.2f} N")

    pipeline.visualize(inputs=list(inputs.keys()),
                       output_path="results/wing_mda",
                       orientation="LR",
                       graph_type="bipartite",
                       view=False)

if __name__ == "__main__":
    run_wing_mda()
